### ISSUE TITLE
default_ccache_name and '%'

### ISSUE THREAD

**Issue by nohaj** [pfmooney/puppet-mit_krb5#13]
Hello,

I would like to do something like that :

mit_krb5::default_ccache_name: 'KEYRING:persistent:%{uid}'

But it's not working with the '%'.

In krb5.conf, i get : 

default_ccache_name = KEYRING:persistent:

With mit_krb5::default_ccache_name: 'KEYRING:persistent:{uid}' i get default_ccache_name = KEYRING:persistent:{uid} so i think that the '%' is the problem.

Regards,

Johan

**Comment by marszip** [comment]
Hi Johan,

What worked for me was the following:

  mit_krb5::default_ccache_name: "KEYRING:persistent:%{literal('%')}{uid}"

In krb5.conf this results in: 

  default_ccache_name = KEYRING:persistent:%{uid}

Regards, 

Marcel

**Comment by nohaj** [comment]
Thank you marszip !
