### ISSUE TITLE
issue with concat ? 

### ISSUE THREAD

**Issue by leshiynyc** [pfmooney/puppet-mit_krb5#5]
Hi, 

I seem to be getting something like this 
Error: Order cannot contain '/', ':', or '
'. at  /path/to/modules/concat/manifests/fragment.pp:46 on node puppetagent1.vagrant.vm
Error: Order cannot contain '/', ':', or '
'. at  /path/to/modules/concat/manifests/fragment.pp:46 on node puppetagent1.vagrant.vm

Traced it down to mit_krb5::realm and mit_krb5::domain_realm

  mit_krb5::realm { 'REALM.EXAMPLE.COM':
    kdc            => 'kdc.server.com:88',
    admin_server   => 'kpasswd.insecure.local',
    default_domain => 'domain.com',
  } # end of realm

  mit_krb5::domain_realm { 'REALM.EXAMPLE.COM':
    domains => $domains,
  } # end of domain_realm

**Comment by leshiynyc** [comment]
I have the same problem.

**Comment by djjudas21** [comment]
This is indeed the issue. The `order` parameter should be a string or a number and must not contain special characters. You could get away with `21realm::${realm}::${title}` (i.e. just the string, no punctuation, so you can still alphabetise) but it would be even nicer if it was just an integer.

**Comment by djjudas21** [comment]
This should be fixed in #6

**Comment by pfmooney** [comment]
I pushed an updated version.
Please test and let me know how it goes.

**Comment by djjudas21** [comment]
Due to the archaic module deployment at my site, we can only run modules from the Forge, not from git repos. We don't have any dev environment for third-party modules.

However, the change looks fine to me - the important bits are identical to my pull reques ;)

**Comment by jd-daniels** [comment]
Change works for me in test. We also can only pull changes directly from forge for prod.

**Comment by pfmooney** [comment]
Thanks for testing.  v0.0.6 has been published to the forge.
